# This is a workflow to complete practicals

name: Example 1
on: workflow_dispatch
jobs:
  example1:
    runs-on: ubuntu-latest 
    steps:
      - name: Get code
        uses: actions/checkout@v3 
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm test
      - name: Build
        run: npm run build
      - name: dummy deploy
        run: |
          echo "deploying..."
          echo "deployed!"
